### PR TITLE
Feature/reqon query

### LINKED ISSUE #7: Implement new query API
Montage is getting a new data querying endpoint that will supersede the existing schema-specific query endpoints. Docs and examples are still forthcoming, but it will be heavily based on [ReQON](https://github.com/dmpayton/reqon).

Any discussion on implementing the new endpoint in the JS wrapper should happen here.

### PR DESCRIPTION
**Pull request by dphaener**
Fixes #7 

@zbyte64: Your eyes on this would be appreciated. I will update the docs when we agree that the implementation is where it needs to be.

@msoghoian: If you would like to have any input on this, it is welcomed.

This adds the new ReQON query style to the underlying mechanics of the wrapper. The external API has changed minimally for the query object, you now have to initialize it with the name of the schema for that query. There is a change to the method of querying the API for documents.

Because you can now execute batch queries, you must "namespace" your query requests:

```js
let query1 = new Query("movies").where({rating__gt: 5})
let query2 = new Query("movies").where({rating__lt: 2})
client.documents({ 'query-1': query1.toJS(), 'query-2': query2.toJS() })
```

This will return a result set like so:
```js
{
  data: {
    'query-1': [ results... ],
    'query-2': [ results... ]
  }
}
```

### CODE REVIEW

**Comment by dphaener** [comment]
@zbyte64 Updated a few things. I think this is ready to ship.

**Comment by zackify** [comment]
:+1:

**Comment by dphaener** [comment]
Except for the failing build. :/

**Comment by dphaener** [comment]
@zbyte64 I'm going to merge this unless you have any objections. I'd like to get it merged and pushed up to NPM tonight/early tomorrow so I can begin some work in using it on Aggregator.

**Comment by dphaener** [comment]
@zbyte64 ping

**Pull request merged**
